### ISSUE TITLE
Reorganization

### ISSUE THREAD

**Issue by zdroid** [openfaux/openfaux-client#25]
**This issue is just for planning, don't close it so far.**

We should reorganize repo, as mentioned before.

All of directories should be in new repositories, with following directory organization:

```
 src/ -- extension code
 meta files -- like readme
```

Chrome extension should stay in this repo, to keep contributions, and speed up reorganization. `chrome/` should be renamed to `src/` in this repo.

**Comment by zlatanvasovic** [comment]
RIP :chart_with_downwards_trend:
